// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sgotipy.proto

package sgotipy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSgotipyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType    string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scope        string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	ExpiresIn    int32  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken string `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *StartSgotipyRequest) Reset() {
	*x = StartSgotipyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgotipy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSgotipyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSgotipyRequest) ProtoMessage() {}

func (x *StartSgotipyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgotipy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSgotipyRequest.ProtoReflect.Descriptor instead.
func (*StartSgotipyRequest) Descriptor() ([]byte, []int) {
	return file_sgotipy_proto_rawDescGZIP(), []int{0}
}

func (x *StartSgotipyRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StartSgotipyRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *StartSgotipyRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StartSgotipyRequest) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *StartSgotipyRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type StartSgotipyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StartSgotipyResponse) Reset() {
	*x = StartSgotipyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgotipy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSgotipyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSgotipyResponse) ProtoMessage() {}

func (x *StartSgotipyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgotipy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSgotipyResponse.ProtoReflect.Descriptor instead.
func (*StartSgotipyResponse) Descriptor() ([]byte, []int) {
	return file_sgotipy_proto_rawDescGZIP(), []int{1}
}

func (x *StartSgotipyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopSgotipyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopSgotipyRequest) Reset() {
	*x = StopSgotipyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgotipy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSgotipyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSgotipyRequest) ProtoMessage() {}

func (x *StopSgotipyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgotipy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSgotipyRequest.ProtoReflect.Descriptor instead.
func (*StopSgotipyRequest) Descriptor() ([]byte, []int) {
	return file_sgotipy_proto_rawDescGZIP(), []int{2}
}

type StopSgotipyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StopSgotipyResponse) Reset() {
	*x = StopSgotipyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgotipy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSgotipyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSgotipyResponse) ProtoMessage() {}

func (x *StopSgotipyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgotipy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSgotipyResponse.ProtoReflect.Descriptor instead.
func (*StopSgotipyResponse) Descriptor() ([]byte, []int) {
	return file_sgotipy_proto_rawDescGZIP(), []int{3}
}

func (x *StopSgotipyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SgotipyStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SgotipyStatusRequest) Reset() {
	*x = SgotipyStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgotipy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SgotipyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SgotipyStatusRequest) ProtoMessage() {}

func (x *SgotipyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgotipy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SgotipyStatusRequest.ProtoReflect.Descriptor instead.
func (*SgotipyStatusRequest) Descriptor() ([]byte, []int) {
	return file_sgotipy_proto_rawDescGZIP(), []int{4}
}

type SgotipyStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SgotipyStatusResponse) Reset() {
	*x = SgotipyStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgotipy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SgotipyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SgotipyStatusResponse) ProtoMessage() {}

func (x *SgotipyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgotipy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SgotipyStatusResponse.ProtoReflect.Descriptor instead.
func (*SgotipyStatusResponse) Descriptor() ([]byte, []int) {
	return file_sgotipy_proto_rawDescGZIP(), []int{5}
}

func (x *SgotipyStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_sgotipy_proto protoreflect.FileDescriptor

var file_sgotipy_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb1, 0x01, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x67, 0x6f, 0x74,
	0x69, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x67, 0x6f,
	0x74, 0x69, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x53,
	0x74, 0x6f, 0x70, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x16, 0x0a, 0x14,
	0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x15, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xc6, 0x01, 0x0a, 0x07, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70,
	0x79, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70,
	0x79, 0x12, 0x14, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x12,
	0x13, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x67, 0x6f, 0x74, 0x69,
	0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d,
	0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e,
	0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x53, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x67, 0x6f, 0x74, 0x69, 0x70, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sgotipy_proto_rawDescOnce sync.Once
	file_sgotipy_proto_rawDescData = file_sgotipy_proto_rawDesc
)

func file_sgotipy_proto_rawDescGZIP() []byte {
	file_sgotipy_proto_rawDescOnce.Do(func() {
		file_sgotipy_proto_rawDescData = protoimpl.X.CompressGZIP(file_sgotipy_proto_rawDescData)
	})
	return file_sgotipy_proto_rawDescData
}

var file_sgotipy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sgotipy_proto_goTypes = []interface{}{
	(*StartSgotipyRequest)(nil),   // 0: StartSgotipyRequest
	(*StartSgotipyResponse)(nil),  // 1: StartSgotipyResponse
	(*StopSgotipyRequest)(nil),    // 2: StopSgotipyRequest
	(*StopSgotipyResponse)(nil),   // 3: StopSgotipyResponse
	(*SgotipyStatusRequest)(nil),  // 4: SgotipyStatusRequest
	(*SgotipyStatusResponse)(nil), // 5: SgotipyStatusResponse
}
var file_sgotipy_proto_depIdxs = []int32{
	0, // 0: Sgotipy.StartSgotipy:input_type -> StartSgotipyRequest
	2, // 1: Sgotipy.StopSgotipy:input_type -> StopSgotipyRequest
	4, // 2: Sgotipy.SgotipyStatus:input_type -> SgotipyStatusRequest
	1, // 3: Sgotipy.StartSgotipy:output_type -> StartSgotipyResponse
	3, // 4: Sgotipy.StopSgotipy:output_type -> StopSgotipyResponse
	5, // 5: Sgotipy.SgotipyStatus:output_type -> SgotipyStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sgotipy_proto_init() }
func file_sgotipy_proto_init() {
	if File_sgotipy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sgotipy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSgotipyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sgotipy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSgotipyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sgotipy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSgotipyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sgotipy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSgotipyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sgotipy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SgotipyStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sgotipy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SgotipyStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sgotipy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sgotipy_proto_goTypes,
		DependencyIndexes: file_sgotipy_proto_depIdxs,
		MessageInfos:      file_sgotipy_proto_msgTypes,
	}.Build()
	File_sgotipy_proto = out.File
	file_sgotipy_proto_rawDesc = nil
	file_sgotipy_proto_goTypes = nil
	file_sgotipy_proto_depIdxs = nil
}
